apiVersion: apps/v1
kind: Deployment
metadata:
  name: explore-mfg-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: explore-demo
  template:
    metadata:
      labels:
        app: explore-demo
    spec:
      containers:
      - name: explore-demo
        image: kmikholap/explore-mfg-demo:latest  # Update with your Docker image
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "demo-main-torch"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: explore-demo-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: explore-demo
  ports:      
    - port: 5000  
      nodePort: 30050
