apiVersion: v1
kind: Namespace
metadata:
  name: cv-app1
---
apiVersion: v1
kind: Pod
metadata:
  name: openvino
  namespace: cv-app1
  labels:
    run: openvino
spec:
  hostNetwork: true
  containers:
  - name: openvino
    image: kangwarn/ubuntu-openvino-dev:v1
    args:
    - bash
    - -c
    - source /root/openvino_env/bin/activate && cd /root/openvino_notebooks && jupyter lab notebooks --allow-root --ip=0.0.0.0 --port=8888
    volumeMounts:
    - mountPath: /dev
      name: devdir
    - mountPath: /sys
      name: sysdir
    securityContext:
      privileged: true
  volumes:
  - name: sysdir
    hostPath:
      path: /sys
      type: Directory
  - name: devdir
    hostPath:
      path: /dev
      type: Directory
  dnsPolicy: ClusterFirst
  restartPolicy: Always
